version: '3.9'

services:
  # Angular Project
  angular:
    build:
      context: ./angular
      dockerfile: Dockerfile
    container_name: test-angular

  # React App (Create React App)
  create-react-app:
    build:
      context: ./create-react-app
      dockerfile: Dockerfile
    container_name: test-react
    

  # Nuxt Project
  nuxt:
    build:
      context: ./nuxt
      dockerfile: Dockerfile
    container_name: test-nuxt
  

  # Vite Project
  vite:
    build:
      context: ./vite
      dockerfile: Dockerfile
    container_name: test-vite
  

  # SvelteKit Project
  sveltekit:
    build:
      context: ./sveltekit
      dockerfile: Dockerfile
    container_name: test-sveltekit
    

  # Vue Project
  vue:
    build:
      context: ./vue
      dockerfile: Dockerfile
    container_name: test-vue


  # Astro Project
  astro:
    build:
      context: ./astro
      dockerfile: Dockerfile
    container_name: test-astro
  

  # Solid Project
  solid:
    build:
      context: ./solid
      dockerfile: Dockerfile
    container_name: test-solid
   

  # Remix Project
  remix:
    build:
      context: ./remix
      dockerfile: Dockerfile
    container_name: test-remix
  

  # Fastify Static Project
  fastify-static:
    build:
      context: ./fastify-static
      dockerfile: Dockerfile
    container_name: test-fastify
  

  # Sails Project
  sails:
    build:
      context: ./sails
      dockerfile: Dockerfile
    container_name: test-sails
  


